Fix linux_bionic build
After adding "toybox" to cvd-host_package.tar.gz,
aosp_cf_arm64_phone-userdebug failed to build with error:

  In file included from external/toybox/lib/args.c:10:
  external/toybox/toys.h:8:10: fatal error: 'generated/config.h' file
  not found
  #include "generated/config.h"
           ^~~~~~~~~~~~~~~~~~~~
  1 error generated.

This is because toybox is not configured to be built on linux_bionic
host, and aosp_cf_arm64_phone is trying to build the HOST_CROSS variant
of toybox, which is arm64 linux_bionic.

Bug: 185883642
Test: lunch aosp_cf_arm64_phone-userdebug && m
Change-Id: I64418fb5f88f8a8b8b7e6905b58cc1f7e68ab2e8